### PR TITLE
Traditional Chinese translation

### PR DESCRIPTION
**Pull request by kamiya10**

### CODE REVIEW

**Comment by NyaomiDEV** [comment]
Thanks a lot!

**Comment by NyaomiDEV** [comment]
@kamiya10 Can you please test out the latest changes to Sunamu? I am not sure if I pick up on the "-tw" part correctly for now, and I want to be sure it works.

**Comment by kamiya10** [comment]
It's working fine and smooth. 👍 
image
image

**Comment by NyaomiDEV** [comment]
Wait a minute, which Spotify client are you using? Can you perhaps hop in Discord? That Spotify logo over there is a BIG no on my book.

**Comment by kamiya10** [comment]
I'm running the latest official Windows version without Spotify Premium.

適用 Windows 的 Spotify
1.1.90.859.gf1bb1e36

image
image

**Comment by NyaomiDEV** [comment]
Oh, so it's Windows... I wonder if there is a way to cut around the logo. It doesn't happen on my Windows 11 VM though and I don't have Premium either...

**Comment by NyaomiDEV** [comment]
Screenshot_20220730_030959

Probably a region-locked thing?

**Comment by kamiya10** [comment]
image

**Comment by NyaomiDEV** [comment]
Windows 11 or 10?

**Comment by kamiya10** [comment]
Windows 10

**Comment by NyaomiDEV** [comment]
Yeah that might be the problem; in Windows 10 SMTC allowed custom ratio album art and Spotify probably decided to "put the extra space to use". In Windows 11, however, the cover art is squared and probably they did not want to risk it.

**Pull request merged**
