### PR TITLE
Support Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by aimerneige**
As in title.

Jsut a little work. I did not do build test.

### CODE REVIEW

**Comment by NyaomiDEV** [comment]
if you tested it in the test environment then it is safe to merge; if the translation is untested I won't merge it

**Comment by aimerneige** [comment]
Got it. I will do the test.

**Comment by aimerneige** [comment]
I build a deb package and install it on a clean installed ubuntu 22.04 kvm virtual machine. It works fine.

Screenshot from 2022-09-02 22-19-28
Screenshot from 2022-09-02 22-20-06

**Comment by NyaomiDEV** [comment]
there is a test that was not conducted; does sunamu use simplified chinese in a machine or vm which is configured to use simplified chinese? I mean without uncommenting the language in the config file

**Comment by aimerneige** [comment]
I recoverd vm's snapshot and set the languge to Chinese.
Then I install Sunamu, without touching the config file. It display English.

截图 2022-09-03 12-21-44

**Comment by aimerneige** [comment]
When I try to comment the language config, sunamu just write a newline into it.
```json5
    language: "en",
```

**Comment by NyaomiDEV** [comment]
This is not supposed to happen. Can you do `language: ""` for now?

**Comment by aimerneige** [comment]
> This is not supposed to happen. Can you do `language: ""` for now?

I try this and it works

截图 2022-09-04 01-34-21

**Pull request merged**
